version: '3.8'

services:
  postgres:
    image: postgres:15.3
    build: ./
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Pottery
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  app:
    build: back/
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Pottery
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  scripts:
